services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django-web:
    build: .
    container_name: jj-event-info-board
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      JJCM_BASE: ${JJCM_BASE}
      JJCM_USERNAME: ${JJCM_USERNAME}
      JJCM_PASSWORD: ${JJCM_PASSWORD}
      DJANGO_OIDC_ENABLED: ${DJANGO_OIDC_ENABLED}
      DJANGO_OIDC_CLIENT_ID: ${DJANGO_OIDC_CLIENT_ID}
      DJANGO_OIDC_CLIENT_SECRET: ${DJANGO_OIDC_CLIENT_SECRET}
      DJANGO_OIDC_AUTHORIZATION_ENDPOINT: ${DJANGO_OIDC_AUTHORIZATION_ENDPOINT}
      DJANGO_OIDC_TOKEN_ENDPOINT: ${DJANGO_OIDC_TOKEN_ENDPOINT}
      DJANGO_OIDC_USER_ENDPOINT: ${DJANGO_OIDC_USER_ENDPOINT}
      DJANGO_OIDC_JWKS_ENDPOINT: ${DJANGO_OIDC_JWKS_ENDPOINT}
      DJANGO_OIDC_SIGN_ALGO: ${DJANGO_OIDC_SIGN_ALGO}
    env_file:
      - .env

volumes:
  postgres_data:
