"""
Django settings for eventBoard project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


from dotenv import load_dotenv
load_dotenv()  # take environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool((os.environ.get("DJANGO_DEBUG", "False"))=="True")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "schedule.apps.ScheduleConfig",
    "polymorphic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mozilla_django_oidc",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "eventBoard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "eventBoard.context_processors.oidc_enabled",
                "eventBoard.context_processors.footer_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "eventBoard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# for this tiny installation, sqlite is good enough.
DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.{}'.format(
             os.getenv('DATABASE_ENGINE', 'sqlite3')
         ),
         'NAME': os.getenv('DATABASE_NAME', 'polls'),
         'USER': os.getenv('DATABASE_USERNAME', 'myprojectuser'),
         'PASSWORD': os.getenv('DATABASE_PASSWORD', 'password'),
         'HOST': os.getenv('DATABASE_HOST', '127.0.0.1'),
         'PORT': os.getenv('DATABASE_PORT', 5432),
     }
 }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "de-DE"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/app/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Coping for CSRF-Failures
#https://docs.djangoproject.com/en/5.2/ref/settings/#csrf-trusted-origins
CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#Disable time zone support, making things a lot easier in our case.
USE_TZ = False

# OIDC Authentication (PocketID)
# Access gate (shared password + QR token)
ACCESS_PASSWORD = os.environ.get("ACCESS_PASSWORD", "")
ACCESS_TOKEN = os.environ.get("ACCESS_TOKEN", "")

OIDC_ENABLED = os.environ.get("DJANGO_OIDC_ENABLED", "False") == "True"

BOARD_MAIN_SECONDS = int(os.environ.get("BOARD_MAIN_SECONDS", 20))
BOARD_DETAIL_SECONDS = int(os.environ.get("BOARD_DETAIL_SECONDS", 20))

if OIDC_ENABLED:
    AUTHENTICATION_BACKENDS = [
        'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]

    OIDC_RP_CLIENT_ID = os.environ.get('DJANGO_OIDC_CLIENT_ID')
    OIDC_RP_CLIENT_SECRET = os.environ.get('DJANGO_OIDC_CLIENT_SECRET')
    OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get('DJANGO_OIDC_AUTHORIZATION_ENDPOINT')
    OIDC_OP_TOKEN_ENDPOINT = os.environ.get('DJANGO_OIDC_TOKEN_ENDPOINT')
    OIDC_OP_USER_ENDPOINT = os.environ.get('DJANGO_OIDC_USER_ENDPOINT')
    OIDC_OP_JWKS_ENDPOINT = os.environ.get('DJANGO_OIDC_JWKS_ENDPOINT')
    OIDC_RP_SIGN_ALGO = os.environ.get('DJANGO_OIDC_SIGN_ALGO', 'RS256')

    LOGIN_REDIRECT_URL = '/app/admin/'
    LOGOUT_REDIRECT_URL = '/app/'