# Generated by Django 5.2.6 on 2025-09-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("firstDay", models.DateField()),
                ("lastDay", models.DateField()),
                ("active", models.BooleanField(default=True)),
                ("jjcmHash", models.CharField(blank=True, max_length=64, unique=True)),
                ("jjcmCompetitionId", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedule.event"
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manually Created Time Slot",
                "verbose_name_plural": "Manually Created Time Slots",
                "proxy": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalProvidedSlot",
            fields=[
                (
                    "slot_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schedule.slot",
                    ),
                ),
                ("hash", models.CharField(blank=True, max_length=64, unique=True)),
                ("discipline", models.CharField(blank=True, max_length=200)),
                ("category_name", models.CharField(blank=True, max_length=200)),
                ("type", models.CharField(blank=True, max_length=20)),
                ("tatami", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Externally Provided Time Slot",
                "verbose_name_plural": "Externally Provided Time Slots",
                "proxy": False,
            },
            bases=("schedule.slot",),
        ),
    ]
