# Generated by Django 5.2.7 on 2026-02-18 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dojo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("jjcmDojoId", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("givenName", models.CharField(max_length=64)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("jjcmCompetitorId", models.IntegerField(blank=True, null=True)),
                ("jjcmAgeClass_Id", models.IntegerField(blank=True, null=True)),
                ("jjcmBirthdate", models.DateField(blank=True, null=True)),
                ("jjcmWeight", models.FloatField(blank=True, null=True)),
                ("jjcmWeightClassId", models.IntegerField(blank=True, null=True)),
                ("jjcmRankClassId", models.IntegerField(blank=True, null=True)),
                ("jjcmRankId", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "jjcmSex",
                    models.CharField(
                        blank=True,
                        choices=[("weiblich", "Female"), ("männlich", "Male")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("hash", models.CharField(blank=True, max_length=64, unique=True)),
                (
                    "jjcmCompetitionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedule.event"
                    ),
                ),
                (
                    "jjcmDojoId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="schedule.dojo",
                    ),
                ),
            ],
        ),
    ]
