# Generated by Django 5.2.7 on 2026-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_dojo_competitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "ID",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Rang",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weiß", "White"),
                            ("gelb", "Yellow"),
                            ("orange", "Orange"),
                            ("grün", "Green"),
                            ("blau", "Blue"),
                            ("braun", "Brown"),
                            ("braun mit 1 Streifen", "Brown 1Stripe"),
                            ("braun mit 2 Streifen", "Brown 2Stripe"),
                            ("braun mit 3 Streifen", "Brown 3Stripe"),
                            ("schwarz", "Black"),
                            ("rot-weiß", "Red White"),
                            ("rot", "Red"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "rankClass",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mon-Grad", "Mon"),
                            ("Kyu-Grad", "Kyu"),
                            ("Dan-Grad", "Dan"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("kyu", models.IntegerField(blank=True, null=True)),
                ("dan", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
