# Generated by Django 5.2.7 on 2026-02-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmCompetitionId",
        ),
        migrations.AddField(
            model_name="competitor",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.event",
            ),
        ),
    ]
