# Generated by Django 5.2.7 on 2026-02-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_remove_competitor_jjcmcompetitionid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitor",
            name="hash",
        ),
    ]
