# Generated by Django 5.2.7 on 2026-02-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_remove_competitor_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
