# Generated by Django 5.2.7 on 2026-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_competitor_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="jjcmRegistrationId",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalprovidedslot",
            name="competitors",
            field=models.ManyToManyField(
                blank=True, related_name="slots", to="schedule.competitor"
            ),
        ),
    ]
