# Generated by Django 5.2.7 on 2026-04-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_add_registration_id_and_slot_competitors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitor",
            name="age",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="competition",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="hash",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmAgeClass_Id",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmBirthdate",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmDojoId",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmRankClassId",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmRankId",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmRegistrationId",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmSex",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmWeight",
        ),
        migrations.RemoveField(
            model_name="competitor",
            name="jjcmWeightClassId",
        ),
        migrations.RemoveField(
            model_name="externalprovidedslot",
            name="competitors",
        ),
        migrations.AddField(
            model_name="competitor",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("FEMALE", "weiblich"), ("MALE", "männlich")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competitor",
            name="jjcmCompetitorId",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jjcmRegistrationId",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("jjcmAgeClassId", models.IntegerField(blank=True, null=True)),
                ("jjcmWeightClassId", models.IntegerField(blank=True, null=True)),
                ("jjcmRankClassId", models.IntegerField(blank=True, null=True)),
                ("jjcmRankId", models.CharField(blank=True, max_length=64, null=True)),
                ("jjcmWeight", models.FloatField(blank=True, null=True)),
                ("hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="schedule.event",
                    ),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="schedule.competitor",
                    ),
                ),
                (
                    "dojo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registrations",
                        to="schedule.dojo",
                    ),
                ),
            ],
            options={
                "unique_together": {("competitor", "competition")},
            },
        ),
        migrations.AddField(
            model_name="externalprovidedslot",
            name="registrations",
            field=models.ManyToManyField(
                blank=True, related_name="slots", to="schedule.registration"
            ),
        ),
    ]
