# Generated by Django 5.2.7 on 2026-04-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0008_refactor_competitor_registration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="jjcmWeight",
        ),
    ]
