# Generated by Django 5.2.7 on 2026-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_remove_jjcmweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="jjcmCompetitionId",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="jjcmHash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
