# Generated by Django 5.2.7 on 2026-04-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_fix_event_jjcmhash"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="Competition",
        ),
        migrations.RenameField(
            model_name="slot",
            old_name="event",
            new_name="competition",
        ),
        migrations.AlterModelTable(
            name="competition",
            table="schedule_event",
        ),
    ]
