# Generated by Django 5.2.7 on 2026-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0011_rename_event_to_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="mon",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
