# Generated by Django 5.2.7 on 2026-04-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0012_add_mon_to_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weiß", "White"),
                    ("weiß-gelb", "White Yellow"),
                    ("gelb", "Yellow"),
                    ("weiß-orange", "White Orange"),
                    ("orange", "Orange"),
                    ("weiß-grün", "White Green"),
                    ("grün", "Green"),
                    ("weiß-blau", "White Blue"),
                    ("blau", "Blue"),
                    ("braun", "Brown"),
                    ("braun mit 1 Streifen", "Brown 1Stripe"),
                    ("braun mit 2 Streifen", "Brown 2Stripe"),
                    ("braun mit 3 Streifen", "Brown 3Stripe"),
                    ("schwarz", "Black"),
                    ("rot-weiß", "Red White"),
                    ("rot", "Red"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jjcmCategoryId", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("RandomAttack", "Random Attack"),
                            ("GroundFighting", "Ground Fighting"),
                            ("GroundFightingOpen", "Ground Fighting Open"),
                            ("Pairs", "Pairs"),
                            ("Kata", "Kata"),
                            ("Team", "Team"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "ageClassName",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("ageClassId", models.IntegerField(blank=True, null=True)),
                ("ageClassMin", models.IntegerField(blank=True, null=True)),
                (
                    "weightClassName",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("weightClassId", models.IntegerField(blank=True, null=True)),
                (
                    "rankClassName",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("rankClassId", models.IntegerField(blank=True, null=True)),
                (
                    "cardinality",
                    models.IntegerField(default=0, help_text="Number of entries"),
                ),
                ("hasGames", models.BooleanField(default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="schedule.competition",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["discipline", "name"],
                "unique_together": {("competition", "jjcmCategoryId")},
            },
        ),
    ]
