# Generated by Django 5.2.7 on 2026-04-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("schedule", "0013_add_category_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jjcmEntryId", models.IntegerField(unique=True)),
                ("overrideCategoryId", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="schedule.category",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="schedule.competition",
                    ),
                ),
                (
                    "dojo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="schedule.dojo",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.CreateModel(
            name="KataEntry",
            fields=[
                (
                    "entry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schedule.entry",
                    ),
                ),
                (
                    "tori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kata_entries_as_tori",
                        to="schedule.registration",
                    ),
                ),
                (
                    "uke",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kata_entries_as_uke",
                        to="schedule.registration",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kata Entries",
            },
            bases=("schedule.entry",),
        ),
        migrations.CreateModel(
            name="PairsEntry",
            fields=[
                (
                    "entry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schedule.entry",
                    ),
                ),
                (
                    "competitor_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_entries_as_a",
                        to="schedule.registration",
                    ),
                ),
                (
                    "competitor_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs_entries_as_b",
                        to="schedule.registration",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pairs Entries",
            },
            bases=("schedule.entry",),
        ),
        migrations.CreateModel(
            name="SingleCompetitorEntry",
            fields=[
                (
                    "entry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schedule.entry",
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("RandomAttack", "Random Attack"),
                            ("GroundFighting", "Ground Fighting"),
                            ("GroundFightingOpen", "Ground Fighting Open"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="single_entries",
                        to="schedule.registration",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("schedule.entry",),
        ),
        migrations.CreateModel(
            name="TeamEntry",
            fields=[
                (
                    "entry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schedule.entry",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="team_entries", to="schedule.registration"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Team Entries",
            },
            bases=("schedule.entry",),
        ),
    ]
