# Generated by Django 5.2.7 on 2026-04-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_add_result_to_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='jjcmCategoriesHash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='jjcmEntriesHash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
