# Generated by Django 6.0.4 on 2026-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_add_entries_categories_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlecompetitorentry',
            options={},
        ),
        migrations.AddField(
            model_name='slot',
            name='show_on_detail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
