# Generated by Django 6.0.4 on 2026-04-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_slot_show_on_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('highlighted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.competition')),
            ],
            options={
                'verbose_name': 'Ticker Message',
                'verbose_name_plural': 'Ticker Messages',
                'ordering': ['order'],
            },
        ),
    ]
